-- Константы для duel_match3.lua: require("modules.duel_match3_config") или require("duel_match3_config")
-- в зависимости от runtime.path (см. комментарий в duel_match3.lua).
return {
  SIZE = 6,
  HEIGHT = 8,
  ACTIVE_Y_MIN = 2,
  ACTIVE_ROWS = 6,
  MAX_HP = 150,
  MAX_MANA = 100,
  TURN_SECONDS = 30,
  TICK_RATE = 6,
  BOT_THINK_SECONDS = 5.0,
  BOT_THINK_TICKS = math.max(1, math.floor(5.0 * 6 + 0.5)),
  -- Задержка между ходами бота в одном «сегменте» (доп. ход, петарда и т.д.), после анимаций (OP 17).
  BOT_THINK_SECONDS_FAST = 2.5,
  BOT_THINK_TICKS_FAST = math.max(1, math.floor(2.5 * 6 + 0.5)),
  CROSS_ABILITY_COST = 20,
  SQUARE_ABILITY_COST = 20,
  PETARD_ABILITY_COST = 30,
  SHIELD_ABILITY_COST = 40,
  FURY_ABILITY_COST = 30,
  CROSS_ABILITY_COOLDOWN = 2,
  SQUARE_ABILITY_COOLDOWN = 2,
  PETARD_ABILITY_COOLDOWN = 1,
  SHIELD_ABILITY_COOLDOWN = 1,
  FURY_ABILITY_COOLDOWN = 2,
  ABILITY_BASE_DAMAGE = 3,
  PETARD_DAMAGE = 15,
  SKULL_DAMAGE = 5,
  ANKH_HEAL = 1,
  FURY_CRIT_CHANCE = 0.18,
  SHIELD_DURATION_TURNS = 3,
  SHIELD_MAX_STACKS = 3,
  SHIELD_ARMOR_PER_STACK = 4,
  SHIELD_HEAL_PER_STACK = 3,
  GEM_MANA = { [1] = 5, [2] = 3, [3] = 1 },
  SPAWN_POOL = { 1, 2, 3, 4, 5 },
  FROZEN_ABILITY_COST_BONUS = 10,
  ACID_HP_LOSS_PCT = 0.03,
  REGEN_HP_PCT = 0.03,
  CHEAT_ROWS_COUNT = 2,
  CHEAT_ROWS_TOTAL = 6 * 2,
  CHEAT_WHITELIST_COLLECTION = "duel_match3_cheat_whitelist",
  CHEAT_WHITELIST_KEY = "emails",
  CHEAT_WHITELIST_USER_ID = "global",
  DEFAULT_CHEAT_EMAILS = { "tminn91@mail.ru" },
  OP_BOARD_SYNC = 10,
  OP_GAME_OVER = 11,
  OP_PLAYER_LEFT = 12,
  OP_ACTION_REQUEST = 13,
  OP_ACTION_REJECT = 14,
  OP_SELECTION_SYNC = 15,
  OP_SNAPSHOT_REQUEST = 16,
  STATS_COLLECTION = "duel_match3_stats",
  STATS_KEY = "summary",
  PVE_PROGRESS_COLLECTION = "duel_match3_progress",
  PVE_PROGRESS_KEY = "profile",
  CHARACTER_SHEET_COLLECTION = "duel_match3_character",
  CHARACTER_SHEET_KEY = "sheet",
  ITEM_DEFS_COLLECTION = "duel_match3_item_defs",
  ITEM_DEFS_KEY = "catalog",
  ITEM_DEFS_STORAGE_USER_ID = "4ad57156-201b-4abf-8d5d-7b4ed6a0364c",
  BOTS_COLLECTION = "duel_match3_bot_defs",
  BOTS_KEY = "catalog",
  --- Дополнительные каталоги по сложности шахты (фаза 3): перекрывают id из BOTS_KEY и BOTS_FALLBACK.
  BOTS_KEYS_BY_DIFFICULTY = {
    easy = "catalog_easy",
    medium = "catalog_medium",
    hard = "catalog_hard",
  },
  BOTS_STORAGE_USER_ID = "4ad57156-201b-4abf-8d5d-7b4ed6a0364c",
  BOT_USER_ID_PREFIX = "zz-bot-",
  LEVEL_XP = { 0, 100, 320, 804, 1869, 4212, 9367, 20708, 45658, 100548, 221306, 486974 },
  PVE_MAX_LEVEL = 12,
  --- Максимальный запас энергии (покупки, «потолок» для HUD). Реген по времени — только до PVE_ENERGY_REGEN_CAP.
  PVE_ENERGY_MAX_BASE = 20000,
  PVE_ENERGY_REGEN_CAP = 100,
  PVE_ENERGY_REGEN_SECONDS = 60,
  PVE_ENERGY_BUY_MATTER_COST = 1,
  PVE_ENERGY_BUY_MATTER_GRANT = 100,
  PVE_ENERGY_BUY_GOLD_COST = 1000,
  PVE_ENERGY_BUY_GOLD_GRANT = 100,
  WORKSHOP_CRAFT_RUSH_GOLD = 500,
  WORKSHOP_CRAFT_RUSH_SECONDS = 20 * 60,
  PVE_ENTRY_ENERGY_COST = 15,
  MINE_SUMMON_ENERGY_COST = 5,
  MINE_SUMMON_GOLD_COST = 50,
  MINE_DIFFICULTY_DEFAULT = "easy",
  MINE_RESPAWN_NORMAL_SECONDS = 10 * 60,
  MINE_RESPAWN_BOSS_SECONDS = 4 * 60 * 60,
  MINE_MATTER_DROP_CHANCE = 0.10,
  --- Модуль duel_match3_metrics: вклад брони в EHP (чем выше, тем «толще» бот при той же броне).
  METRICS_ARMOR_TO_EHP_K = 0.05,
  --- Сравнение с суммами §3.2 (HP/броня в «тысячах»): EHP_игрока ≈ HP×(1 + armor/REF).
  METRICS_PLAYER_ARMOR_REF = 1000,
  MINE_AFFIX_POOL = {
    "acid",
    "energy_block",
    "regeneration",
    "fragility",
    "stone_skin",
    "mana_vampire",
    "frozen",
    "monster_rage",
    "instability",
    "overload",
    "bare_current",
    "scree",
  },
  SESSION_EPOCH_ACCOUNT_META = "session_epoch",
  --- Зелёный normal T1: синхронно с gen_item_catalog.js (упор на накопление ресурсов).
  -- Fallback без craft_* в каталоге: как зелёный шлем T1 (этаж рецепта 1); по слотам см. duel_match3_item_catalog.
  WORKSHOP_T1_NORMAL_COST = { ore = 350, gold = 300, ingot_def = "ingot_green", ingot_n = 4 },
  WORKSHOP_T2_NORMAL_COST = { ore = 350, gold = 300, ingot_def = "ingot_green", ingot_n = 4 },
  WORKSHOP_T3_NORMAL_COST = { ore = 350, gold = 300, ingot_def = "ingot_green", ingot_n = 4 },
  --- Длительность крафта (секунды); тиры 2–3 не используются в экипе, оставлены для совместимости.
  WORKSHOP_CRAFT_DURATION_SEC_BY_TIER = { [1] = 60 * 60, [2] = 120 * 60, [3] = 240 * 60 },
}
